### ISSUE TITLE
F01 Prijava

### ISSUE THREAD

**Issue by tcosic22** [foivz/POP-App-AiR-Lab-Project-24#1]
Za pristup aplikaciji autentifikacija korisnika putem login funkcionalnosti. Korisnik mora unijeti e-mail i lozinku tijekom procesa prijave.

**Comment by coaltail** [comment]
Poštovanje, 

napravili smo grešku kod kreiranja taska te smo odabrali krivi projekt. Ispričavamo se :).

Lp,

Luka Baksa i Tomislav Ćosić
